# Generated by Django 5.2.4 on 2025-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorrat', '0002_fooditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='unit',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='expiration_date',
            field=models.DateField(verbose_name='Ablaufdatum'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.FloatField(verbose_name='Anzahl'),
        ),
    ]
